### PR TITLE
#8 filter by faculty

### LINKED ISSUE #8: Filter by Faculty
Currently, you can select tags that allow you to filter the search results by faculty, however, the actual filtering aspect has not been implemented yet.

### PR DESCRIPTION
**Pull request by pumbas600**
Closes #8 

Currently, it has not been fully tested as nothing has faculty tags, but the logic *should* work.

### CODE REVIEW

**Comment by NachoToast** [comment]
How did you test this given none of our database entries have tags yet?

**Comment by pumbas600** [comment]
> How did you test this given none of our database entries have tags yet?

Currently I've just tested:
- That selecting a faculty doesn't show any results
- That selecting faculties causes the results to (nearly) instantaneously update
- That unselecting faculties preserves your search
- That changing your search after selecting facilties doesn't overwrite the faculty tag filters

Certainly not robust though...  I'm happy to fully test it once we get some faculty tags added though

**Comment by NachoToast** [comment]
> Certainly not robust though... I'm happy to fully test it once we get some faculty tags added though

Agreed, this LGTM but I will put it on hold until I've migrated tags from the legacy data.

**Comment by NachoToast** [comment]
Currently blocked by:
- https://github.com/UoA-Discords/api/pull/6

**Comment by pumbas600** [comment]
I've tested it now that we have tags on the servers:

Filter by a single tag:
image

Filter by two tags:
image

Filter by two tags and a search:
image

**Comment by pumbas600** [comment]
I just want to add that the server tags were mainly a temporary thing for testing, I'm not sure if they're too bulky so if they need to be changed that's fine

**Comment by NachoToast** [comment]
I've merged the functionality of searching by tags and by text.
I've also removed the debounce for tag searching since we're actually fast enough to even search on text input change.

**Review by NachoToast — APPROVED** [review]

**Pull request merged**
